### ISSUE TITLE
Which explanations to return by default for text?

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna-exploration#138]
While exploring #125, we ran into the issue that LIME and RISE now return different things. For RISE's `explain_text`, we decided to return the scores of all labels, while for LIME we have a `label` keyword argument that can be used to select only one. LIME in principle allows for selecting a list of labels, but this may slow things down (we should check this).

We should uniformize this. So either:
1. RISE `explain_text` should get a `label` keyword or
2. LIME `explain_text` should return all labels as well.

Then we can continue with building text visualization functions.

Let's ponder as well what this entails for images.

**Comment by cwmeijer** [comment]
I have been trying to test LIME with all labels possible to mimic RISE's behavior. I ran into the following problem. For LIME we need to give a list of label indices as an argument. We cannot know how many labels a model outputs without running the model, because we cannot be sure what kind of object the model is. The model object might even be a wrapping function in the implementation that we have. We could then run the model once (but with what data?) to count the number of outputs in order to derive the number of labels that we need. This would also be a very hacky, and unnecessarily slow, solution. So I think that rules out option 2 which leaves us with only option 1.

**Comment by cwmeijer** [comment]
In PR https://github.com/dianna-ai/dianna/pull/21 I implemented option 1.
