### ISSUE TITLE
Get the medical dataset (https://camelyon17.grand-challenge.org/)

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#46]

**Comment by geek-yang** [comment]
The CAMELYON17 dataset is too large to fit into our surfdrive (~600GB). Since there are multiple ways to easily access the dataset, it is better to keep it for now and download it when necessary. The dataset can be accessed via the [page](https://camelyon17.grand-challenge.org/Data/). More information about the data, concerning both training and testing, can be found on this page, too. It also elaborates how to prepare the data for training and testing (medical images in .tiff format).

**Comment by geek-yang** [comment]
The related evaluation criterion as well as the classification info is provided [here](https://camelyon17.grand-challenge.org/Evaluation/). Since the dataset and pre-processing of the data is very well explained, it does not make sense to create another notebook to repeat the process shown on this [page](https://camelyon17.grand-challenge.org/Data/). Therefore, I would like to close this issue for now.
