### ISSUE TITLE
Investigate convertors for MXNet

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#5]
refs #1 
Do these converters exist? 
- [ ] MXNet-> ONNX

Add links to the convertors in the comments below. Also, comment if they were tested and if they work well and such.

**Comment by loostrum** [comment]
MXNet has a builtin ONNX converter: https://mxnet.apache.org/versions/1.5.0/tutorials/onnx/export_mxnet_to_onnx.html
The tutorial is part of the docs of MXNet version 1.5.0, while the latest version is 1.7.0. In 1.7.0, there is no ONNX tutorial. I tried following the 1.5.0. tutorial in version 1.7.0, but then conversion to ONNX fails with an error:

`ValidationError: Unrecognized attribute: spatial for operator BatchNormalization`

**Comment by loostrum** [comment]
It also failed with MXNet 1.5.0, same error. [this issue](https://github.com/apache/incubator-mxnet/issues/14589) suggests the onnx version may be too new. Exporting does indeed work with onnx version 1.3.0. TBC if the exported model gives the same results as the original MXNet model.

**Comment by loostrum** [comment]
Still running into issues: the model generated with MXNet 1.7.0 and onnx 1.3.0 is not valid ONNX. 
Specific error: `InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running BatchNormalization node. Name:'bn_data' Status Message: Invalid input scale: NumDimensions() != 3`

This can be fixed by setting `spatial = 1 ` for BatchNorm layer in `mxnet/contrib/onnx/mx2onnx/_op_translations.py`; following https://github.com/microsoft/onnxruntime/issues/2045

Conclusion: MXNet to ONNX convertor exists, but does not work very well
