### ISSUE TITLE
Apply new directory/file structure for the model generation/preparation scripts

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#65]

**Comment by loostrum** [comment]
I think it's nice to have everything related to these datasets in one folder as opposed to having separate folders in the root of the repo. To keep things organized, we could still have separate subfolders for the different things we do with the data, e.g. like this:

- \<root folder\>
  - example_data (?, Can't think of a better name yet)
    - README.md
    - dataset_preparation (-- everything for creating the dataset as it is stored to surfdrive)
      - README.md 
      - leafsnap
      - mnist
      - etc.
    - model_generation (-- everything to go from surdrive dataset to ONNX model)
      - README.md
      - leafsnap
      - mnist
      - etc.

One thing we should eventually decide is if this repository will also hold the code for the final DIANNA software, i.e. the python package. While we can decide which folders will be part of the actual package, I don't think it make much sense that people that look at the repo because they want to check out the code will also get e.g. the meeting templates folder.

**Comment by egpbos** [comment]
Indeed, it may be better to create a new repo (from the Python cookiecutter template probably) for the package.
