### ISSUE TITLE
Test/play with an implementation of Lime

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#81]
At least on the leafs dataset:
- copy a generated heatmap to this issue
- lesson learnt from implementation
- at least a few lines on the user experience

Focus on the question: Can we reuse (parts of) this implementation?

**Comment by loostrum** [comment]
- I could not get LIME in captum to work, always got some error (weights summing to zero). Other captum methods did work fine on the exact same data so I'm not sure what the issue is.
- The implementation by the author (https://github.com/marcotcr/lime) did work. It is quite easy to use too and agnostic to the framework used for the model. An interesting different with the captum implementation is that captum requires the user to define the features (i.e. superpixels for images), while the reference implementation can do this automatically.
- Example heatmap of a LeafSnap explanation:

![leafsnap_lime](https://user-images.githubusercontent.com/6370787/124282251-ecb0ba80-db4a-11eb-9890-cfbaa8ec183f.png)


Conclusion: I think we could use the author's implementation in DIANNA. it has a BSD-2 license, so it's fine to either use some of their code or just have it as a dependency and build upon it.
